### PR TITLE
Add support for IT8625E

### PR DESCRIPTION
**Pull request by jmaggard10**
This appears to be mostly identical to IT8665E.

### CODE REVIEW

**Comment by groeck** [comment]
Not entirely. In terms of configuration registers it matches it8622, except for AVCC which I think is always enabled. Also, fan_ctl6 ix register 0xd3h:0 == 0, and fan_tac6 is 0xd3:1 == 0 (both in LDN 7).
Temperature sources are almost the same, so that is good enough.

**Comment by jmaggard10** [comment]
Hmm, the current it87.c code for IT8665E already uses `0xd3h:0 == 0` for fan_ctl6, and `0xd3:1 == 0` for fan_tac6, which matches IT8625E.  I don't see any other differences on the chart.

**Comment by groeck** [comment]
Please have a look at the spreadsheet; I added a tab for configuration registers. You are correct, the configuration bits for fan 6 are the same, but the configuration for fans4 and 5 are different and match 8622.

**Comment by jmaggard10** [comment]
Yuck. OK, so would you prefer moving it8625 to its own if statement, or add a new small conditional for fan 4/5 inside the it8665 init code?

**Comment by groeck** [comment]
Yes, isn't if fun. Anyway, your call. Either way is fine with me.

**Comment by jmaggard10** [comment]
OK, that should cover it.

**Comment by groeck** [comment]
Done.

**Pull request closed without merging**
